use online_food_del;
-- 1. Total orders per city

select r.city,count(o.order_id) as orders
from restaurants r join orders o 
on r.restaurant_id=o.restaurant_id
group by r.city
order by orders desc;

-- jaipur,hyderabad,delhi have highest orders compare to other cities
-- most active markets
-- focus on marketing,special offers
-- expansion stratigies
-- improve operations on other cities



-- 2. revenue generated by each food item--

select m.item_name,round(sum(m.price*o.quantity),2) as revenue
from menu_item m join order_details o 
on m.item_id=o.item_id
group by m.item_name
order by revenue desc;

-- insights- best performing food items
-- aloo paratha,fishcurry,hakka noodles are top 3 items generating revenue
-- promote it more prominently on app
-- ensure consitent availabilty and faster delivery

-- 3.Top 5 spending customers

SELECT c.customer_name,
       round(SUM(od.quantity * m.price),2) AS total_spent
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_details od 
    ON o.order_id = od.order_id
JOIN menu_item m 
    ON od.item_id = m.item_id
GROUP BY c.customer_name
ORDER BY total_spent DESC
LIMIT 5;

-- inights: top 5 spending customers
-- improve and give extra offers for these customers
-- finding their tastes,intrest on food items
-- encoraging them more to spend on fooditems




-- 4.Restaurant wise order count

select r.rest_name,count(o.order_id) as order_count 
from restaurants r join orders o 
on r.restaurant_id=o.restaurant_id
group by r.rest_name
order by order_count desc;

-- insights:  golden_garden got highest num of orders
-- golden_diner got least numof orders
-- improving user experience and giving rating to restaurants
-- top 5 restaurants with highest orders





-- 5. Average order value by city

select r.city,round(avg(o.order_id),2) as avg_order_value
from restaurants r join orders o 
on r.restaurant_id=o.restaurant_id
group by r.city
order by avg_order_value desc;

-- insights: delhi has higest avg order value
-- top 5 cities having highest avg_order_value
-- chennai having least avg_order_value
-- encouraging customers of delhi to placemore num of orders

